# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0118e30dc18190f6208de554c319d549"
name = "AIVA"
handle = "aiva-2"
application_url = "https://penetration-dump-hire-reg.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products"

[auth]
redirect_urls = ["https://penetration-dump-hire-reg.trycloudflare.com/auth/callback", "https://penetration-dump-hire-reg.trycloudflare.com/auth/shopify/callback", "https://penetration-dump-hire-reg.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
