# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3364eeff7818f5c233596498ec07fcad"
name = "ecomm-experts-v1"
handle = "ecomm-experts-v1"
application_url = "https://surfaces-silk-standards-routers.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, write_orders"

[auth]
redirect_urls = ["https://surfaces-silk-standards-routers.trycloudflare.com/auth/callback", "https://surfaces-silk-standards-routers.trycloudflare.com/auth/shopify/callback", "https://surfaces-silk-standards-routers.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
